from django.conf.urls import patterns, url
from lab import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^about/goals/$', views.about_goals, name='about_goals'),
    url(r'^about/collaborators/$', views.about_collaborators, name='about_collaborators'),
    url(r'^about/people/$', views.about_people, name='about_people'),
    url(r'^about/literature/$', views.about_literature, name='about_literature'),
		url(r'^error_prelim/$', views.error_prelim, name='error_prelim'),
		url(r'^experiment/(?P<experiment_name_url>\w+)/$', views.experiment, name='experiment'),
		url(r'^register/$', views.register, name='register'),
		url(r'^login/$', views.user_login, name='login'),
		url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^change_password/$', views.profile_change_password, name ='profile_change_password'),
    url(r'^edit_profile/$', views.edit_profile, name ='edit_profile'),
		url(r'^profile/(?P<profile_name>\w+)/$', views.profile, name ='profile'),
		url(r'^goto/$', views.track_url, name='track_url'),
    url(r'^seed_inventory/$', views.seed_inventory, name='seed_inventory'),
    url(r'^seed_inventory/select_pedigree/$', views.select_pedigree, name='select_pedigree'),
    url(r'^seed_inventory/select_taxonomy/$', views.select_taxonomy, name='select_taxonomy'),
    url(r'^seed_inventory/select_stocks/$', views.select_stocks, name='select_stocks'),
    url(r'^seed_inventory/suggest_pedigree/$', views.suggest_pedigree, name='suggest_pedigree'),
    url(r'^seed_inventory/suggest_taxonomy/$', views.suggest_taxonomy, name='suggest_taxonomy'),
    url(r'^seed_inventory/checkbox_clear/(?P<clear_selected>\w+)/$', views.checkbox_seed_inventory_clear, name='checkbox_seed_inventory_clear'),
    )
