SET FOREIGN_KEY_CHECKS = 0;
delete from lab_collecting;
delete from lab_diseaseinfo;
delete from lab_experiment;
delete from lab_field;
delete from lab_isolate;
delete from lab_locality;
delete from lab_location;
delete from lab_measurement;
delete from lab_measurementparameter;
delete from lab_obsplant;
delete from lab_obsrow;
delete from lab_obssample;
delete from lab_obsselector;
delete from lab_passport;
delete from lab_people;
delete from lab_publication;
delete from lab_stock;
delete from lab_stockpacket;
delete from lab_taxonomy;
SET FOREIGN_KEY_CHECKS = 1;